### ISSUE TITLE
Support private OIDs

### ISSUE THREAD

**Issue by johnarnold** [networklore/ansible-snmp-facts#1]
Would you consider an optional dictionary argument of variable->oid, so that people can collect arbitrary private mib stuff?

**Comment by ogenstad** [comment]
Can you give an example of what you want to poll?

This module has been included in Ansible 1.9 so I don't really maintain this repo any longer. But it could fit into a new module in my other repo for [ansible snmp modules](https://github.com/networklore/ansible-snmp).

**Comment by ogenstad** [comment]
No response, closing issue.
