### ISSUE TITLE
No more variables left in this MIB View

### ISSUE THREAD

**Issue by ajl119** [networklore/ansible-snmp-facts#3]
Hi,

We have found that on some Cisco switch models, after upgrading IOS from 12. to 15. we started to get the following error when using snmp_facts;

Traceback (most recent call last):
  File "/tmp/ansible_c6DB23/ansible_module_snmp_facts.py", line 450, in <module>
    main()
  File "/tmp/ansible_c6DB23/ansible_module_snmp_facts.py", line 442, in main
    results['ansible_interfaces'][int(interface)]['ipv4'] = interface_to_ipv4[interface]
ValueError: invalid literal for int() with base 10: 'No more variables left in this MIB View'

fatal: [SWITCHNAME]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_c6DB23/ansible_module_snmp_facts.py\", line 450, in <module>\n    main()\n  File \"/tmp/ansible_c6DB23/ansible_module_snmp_facts.py\", line 442, in main\n    results['ansible_interfaces'][int(interface)]['ipv4'] = interface_to_ipv4[interface]\nValueError: invalid literal for int() with base 10: 'No more variables left in this MIB View'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

It appears to be an issue on the network device side, returning data which snmp_facts is not expecting. So I think it just needs to account for this response.

To test I made the following diff for /usr/local/lib/python2.7/dist-packages/ansible/modules/net_tools/snmp_facts.py;
```
413,414c413,415
<                 ipv4_networks[curIP]['address'] = current_val
<                 all_ipv4_addresses.append(current_val)
---
>                 if current_val != "No more variables left in this MIB View":
>                     ipv4_networks[curIP]['address'] = current_val
>                     all_ipv4_addresses.append(current_val)
442c443,444
<         results['ansible_interfaces'][int(interface)]['ipv4'] = interface_to_ipv4[interface]
---
>         if interface != "No more variables left in this MIB View":
>             results['ansible_interfaces'][int(interface)]['ipv4'] = interface_to_ipv4[interface]
```
This seems to have resolved the issue for us :)
Cheers, Andy

**Comment by ogenstad** [comment]
Sorry about the late response, since Ansible 1.9 this module has been included as a core part of Ansible and I won't do any updates to this one. If the problem still exists in the latest version of Ansible  please open an issue for it over at https://github.com/ansible/ansible/issues

**Comment by shamax2201** [comment]
> Hi,
> 
> We have found that on some Cisco switch models, after upgrading IOS from 12. to 15. we started to get the following error when using snmp_facts;
> 
> Traceback (most recent call last):
> File "/tmp/ansible_c6DB23/ansible_module_snmp_facts.py", line 450, in 
> main()
> File "/tmp/ansible_c6DB23/ansible_module_snmp_facts.py", line 442, in main
> results['ansible_interfaces'][int(interface)]['ipv4'] = interface_to_ipv4[interface]
> ValueError: invalid literal for int() with base 10: 'No more variables left in this MIB View'
> 
> fatal: [SWITCHNAME]: FAILED! => {
> "changed": false,
> "module_stderr": "Traceback (most recent call last):\n File "/tmp/ansible_c6DB23/ansible_module_snmp_facts.py", line 450, in \n main()\n File "/tmp/ansible_c6DB23/ansible_module_snmp_facts.py", line 442, in main\n results['ansible_interfaces'][int(interface)]['ipv4'] = interface_to_ipv4[interface]\nValueError: invalid literal for int() with base 10: 'No more variables left in this MIB View'\n",
> "module_stdout": "",
> "msg": "MODULE FAILURE",
> "rc": 1
> }
> 
> It appears to be an issue on the network device side, returning data which snmp_facts is not expecting. So I think it just needs to account for this response.
> 
> To test I made the following diff for /usr/local/lib/python2.7/dist-packages/ansible/modules/net_tools/snmp_facts.py;
> 
> ```
> 413,414c413,415
> <                 ipv4_networks[curIP]['address'] = current_val
> <                 all_ipv4_addresses.append(current_val)
> ---
> >                 if current_val != "No more variables left in this MIB View":
> >                     ipv4_networks[curIP]['address'] = current_val
> >                     all_ipv4_addresses.append(current_val)
> 442c443,444
> <         results['ansible_interfaces'][int(interface)]['ipv4'] = interface_to_ipv4[interface]
> ---
> >         if interface != "No more variables left in this MIB View":
> >             results['ansible_interfaces'][int(interface)]['ipv4'] = interface_to_ipv4[interface]
> ```
> This seems to have resolved the issue for us :)
> Cheers, Andy

Thanks. Had the same issue. You saved my day.

**Comment by mnhauke** [comment]
The issue still exists in the related ansible core module:
https://github.com/ansible/ansible/issues/49044

**Comment by IcebergTitanic** [comment]
Still present in snmp_facts.py version 1.9. 
Ansible 2.8.4 (via EPEL on Centos7)
pysnmp 4.4.12
Python 2.7.5

Workaround inserted at line 457 was able to work.:

457c457,458
<         results['ansible_interfaces'][int(interface)]['ipv4'] = interface_to_ipv4[interface]
---
>         if interface != "No more variables left in this MIB View":
>               results['ansible_interfaces'][int(interface)]['ipv4'] = interface_to_ipv4[interface]
